"""
Agentic Orchestrator
--------------------

Controls the multi-agent fact-verification workflow.

Unlike pipeline.py, which follows a fixed sequence,
this orchestrator can make decisions based on agent outputs.

Current capabilities:
    - Run Claim Agent
    - Run Evidence Agent
    - Run Verification Agent
    - Stop when evidence supports/refutes the claim
    - Retry when evidence is insufficient
    - Generate improved search queries for retry
    - Preserve subclaim/query provenance during
      the initial evidence retrieval
"""

import json

from groq import Groq
from pydantic import BaseModel

from src.agents.claim_agent import analyze_claim
from src.agents.evidence_agent import retrieve_evidence
from src.agents.verification_agent import (prepare_evidence, verify_claim_by_subclaims, aggregate_subclaim_results)

# Maximum number of evidence retrieval attempts.
MAX_RETRIES = 2

class RetrySearchQuery(BaseModel):
    """
    Structured search query generated by the orchestrator
    during an evidence-retrieval retry.

    Keeping subclaim_id allows the Evidence Agent to continue
    performing per-subclaim ranking on later attempts.
    """

    subclaim_id: str
    query: str

def get_insufficient_subclaim_ids(verification_result):
    """
    Return the IDs of subclaims that could not be
    verified with the currently available evidence.

    Only these subclaims need another retrieval attempt.
    """

    return [
        result.subclaim_id
        for result in verification_result.subclaim_results
        if result.verdict == "INSUFFICIENT"
    ]

# ============================================================
# RETRY QUERY GENERATION
# ============================================================

def generate_retry_queries(claim, subclaims, previous_queries, verification_explanation):
    """
    Generate improved search queries when the previous
    evidence retrieval attempt was insufficient.

    Each generated query must be linked to a valid subclaim.
    """

    # --------------------------------------------------------
    # CREATE GROQ CLIENT
    # --------------------------------------------------------

    try:
        client = Groq()

    except Exception as e:
        print(
            f"Warning: Could not initialize Groq client "
            f"for retry generation: {e}"
        )
        return []

    # --------------------------------------------------------
    # PREPARE SUBCLAIMS FOR THE LLM
    # --------------------------------------------------------

    subclaim_data = [
        {
            "id": subclaim.id,
            "text": subclaim.text
        }
        for subclaim in subclaims
    ]

    prompt = f"""
        You are controlling the evidence retrieval strategy of a
        fact-verification system.

        The previous evidence retrieval attempt was insufficient.

        ORIGINAL CLAIM:
        {claim}

        SUBCLAIMS:
        {json.dumps(subclaim_data, indent=2)}

        PREVIOUS SEARCH QUERIES:
        {json.dumps(previous_queries, indent=2)}

        WHY THE EVIDENCE WAS INSUFFICIENT:
        {verification_explanation}

        Generate improved web search queries that specifically address the missing evidence.

        Every query MUST be linked to one of the provided subclaim IDs.

        Rules:
        - Generate 2 to 4 queries.
        - Use ONLY subclaim IDs listed in SUBCLAIMS.
        - Each query must target the fact expressed by its subclaim.
        - Preserve important entities, dates, locations, events, relationships, negations, and qualifiers.
        - Do not assume the claim is true.
        - Queries must be neutral.
        - Do not simply repeat previous queries.
        - Focus on information missing from the previous evidence.
        - If a particular subclaim lacks sufficient evidence, prioritize queries for that subclaim.
        - Do not invent new subclaims.
        - Return ONLY valid JSON.

        Required format:

        {{
            "queries": [
                {{
                    "subclaim_id": "c1",
                    "query": "improved neutral search query"
                }},
                {{
                    "subclaim_id": "c2",
                    "query": "improved neutral search query"
                }}
            ]
        }}
    """

    # --------------------------------------------------------
    # CALL GROQ
    # --------------------------------------------------------

    # Retry-query generation is helpful, but it should not
    # crash the complete verification workflow if Groq fails.
    try:
        response = client.chat.completions.create(
            model="openai/gpt-oss-120b",
            temperature=0,
            max_tokens=500,
            messages=[
                {"role": "user", "content": prompt}
            ]
        )

    except Exception as e:
        print(
            f"Warning: Retry query generation failed: {e}"
        )
        return []

    # --------------------------------------------------------
    # READ MODEL RESPONSE
    # --------------------------------------------------------

    try:
        text = response.choices[0].message.content

        if not text:
            print("Warning: Retry query generator returned an empty response.")
            return []

        text = text.strip()

    except (AttributeError, IndexError, TypeError) as e:
        print(f"Warning: Invalid retry-query response: {e}")
        return []

    # Remove Markdown code fences if the model adds them.
    if text.startswith("```"):
        text = text.strip("`")

        if text.startswith("json"):
            text = text[4:].strip()

    # --------------------------------------------------------
    # PARSE JSON
    # --------------------------------------------------------

    try:
        data = json.loads(text)

    except json.JSONDecodeError as e:
        print(
            f"Warning: Retry query generator returned "
            f"invalid JSON: {e}"
        )
        return []

    raw_queries = data.get("queries", [])

    # Make sure "queries" is actually a list.
    if not isinstance(raw_queries, list):
        print("Warning: Retry query generator returned an invalid queries structure.")
        return []

    # --------------------------------------------------------
    # VALIDATE SUBCLAIM IDs
    # --------------------------------------------------------

    valid_subclaim_ids = {subclaim.id for subclaim in subclaims}

    retry_queries = []

    for item in raw_queries:

        # Ignore malformed query entries.
        if not isinstance(item, dict):
            continue

        subclaim_id = item.get("subclaim_id")
        query = item.get("query", "")

        # Make sure query is a string before calling strip().
        if not isinstance(query, str):
            continue

        query = query.strip()

        # Ignore malformed queries.
        if not query:
            continue

        # Do not allow the LLM to invent subclaim IDs.
        if subclaim_id not in valid_subclaim_ids:
            continue

        retry_queries.append(
            RetrySearchQuery(
                subclaim_id=subclaim_id,
                query=query
            )
        )

    return retry_queries

# ============================================================
# AGENTIC ORCHESTRATOR
# ============================================================

def run_agentic_orchestrator(user_claim: str):
    """
    Run the agentic fact-verification workflow.
    """

    print("\n==========================================")
    print("       AGENTIC FACT VERIFICATION")
    print("==========================================")

    # ========================================================
    # STEP 1: CLAIM ANALYSIS
    # ========================================================

    print("\n========== CLAIM AGENT ==========")

    analysis = analyze_claim(user_claim)

    print("Status:", analysis.status)

    print("\nSubclaims:")
    for subclaim in analysis.subclaims:
        print(
            f"{subclaim.id}: "
            f"{subclaim.text}"
        )

    print("\nSearch Queries:")
    for search in analysis.search_queries:
        print(
            f"{search.subclaim_id}: "
            f"{search.query}"
        )

    # ========================================================
    # STEP 2: HANDLE AMBIGUOUS CLAIMS
    # ========================================================

    if analysis.status == "needs_clarification":

        print(
            "\n========== ORCHESTRATOR DECISION =========="
        )

        print(
            "Claim requires clarification."
        )

        print("\nAmbiguities:")
        for ambiguity in analysis.ambiguities:
            print("-", ambiguity)

        return {
            "status": "needs_clarification",
            "analysis": analysis,
            "evidence_result": None,
            "verification_result": None
        }

    # ========================================================
    # STEP 3: PREPARE INITIAL SEARCH QUERIES
    # ========================================================

    # IMPORTANT:
    #
    # Previously we converted SearchQuery objects into strings.
    #
    # Now we preserve the complete objects so that the
    # Evidence Agent knows which query belongs to which
    # subclaim.
    search_queries = analysis.search_queries
    evidence_result = None
    verification_result = None

    # Attempt 1 starts with all subclaims.
    current_subclaims = analysis.subclaims

    # Preserve resolved subclaim results across retries.
    resolved_subclaim_results = {}

    # Evidence IDs must remain unique across attempts.
    next_evidence_id = 1

    # ========================================================
    # STEP 4: AGENTIC RETRY LOOP
    # ========================================================

    for attempt in range(1, MAX_RETRIES + 1):

        print(
            f"\n========== EVIDENCE ATTEMPT "
            f"{attempt}/{MAX_RETRIES} =========="
        )

        # ----------------------------------------------------
        # CALL EVIDENCE AGENT
        # ----------------------------------------------------

        evidence_result = retrieve_evidence(
            claim=analysis.original_claim,
            search_queries=search_queries,
            subclaims=current_subclaims
        )

        evidence_count = len(evidence_result["evidence"])

        print(
            f"\nRetrieved {evidence_count} "
            "evidence item(s)."
        )

        # ====================================================
        # DISPLAY EVIDENCE PROVENANCE
        # ====================================================

        # This allows us to verify that each evidence item
        # remembers which subclaim/query retrieved it.
        print("\nEvidence Provenance:")

        for index, item in enumerate(evidence_result["evidence"], start=1):
            print(
                f"[{index}] "
                f"Subclaim: {item.get('subclaim_id')} | "
                f"Query: {item.get('query')} | "
                f"URL: {item.get('url')}"
            )

        # ====================================================
        # PREPARE EVIDENCE FOR VERIFICATION AGENT
        # ====================================================

        verification_evidence = prepare_evidence(evidence_result["evidence"], start_id=next_evidence_id)

        next_evidence_id += len(verification_evidence)

        print("\nEvidence received by Verification Agent:")

        for item in verification_evidence:
            print(
                f"Evidence {item.id} | "
                f"Subclaim: {item.subclaim_id} | "
                f"Query: {item.query}"
            )

        # ----------------------------------------------------
        # CALL VERIFICATION AGENT
        # ----------------------------------------------------

        print("\n========== VERIFICATION AGENT ==========")

        # ====================================================
        # VERIFY ONLY THE SUBCLAIMS FOR THIS ATTEMPT
        # ====================================================

        current_verification_result = verify_claim_by_subclaims(subclaims=current_subclaims, evidence=verification_evidence)

        # ====================================================
        # PRESERVE RESOLVED SUBCLAIMS
        # ====================================================
        #
        # If a subclaim has already reached SUPPORTED or
        # REFUTED, we keep that result for later attempts.
        #
        # Example:
        #
        # Attempt 1:
        #   c1 -> SUPPORTED
        #   c2 -> INSUFFICIENT
        #
        # c1 is stored here while c2 is retried.

        for result in current_verification_result.subclaim_results:
            if result.verdict in {"SUPPORTED","REFUTED"}:
                resolved_subclaim_results[result.subclaim_id] = result

        # ====================================================
        # COMBINE OLD RESULTS WITH CURRENT RESULTS
        # ====================================================
        #
        # Start with subclaims that were already resolved
        # during previous attempts.

        combined_results = dict(resolved_subclaim_results)

        # Add/replace the results produced during the
        # current attempt.
        #
        # This also keeps INSUFFICIENT results so that the
        # orchestrator knows which subclaims still need work.

        for result in current_verification_result.subclaim_results:
            combined_results[result.subclaim_id] = result

        # ====================================================
        # RECALCULATE THE OVERALL CLAIM VERDICT
        # ====================================================
        #
        # Example after retry:
        #
        # preserved c1 -> SUPPORTED
        # new c2       -> INSUFFICIENT
        #
        # Overall      -> INSUFFICIENT

        verification_result = aggregate_subclaim_results(list(combined_results.values()))

        print("\nSubclaim Verification Results:")

        for result in verification_result.subclaim_results:

            print(
                f"\n{result.subclaim_id}: "
                f"{result.subclaim_text}"
            )

            print(
                f"Verdict: {result.verdict}"
            )

            print(
                f"Confidence: {result.confidence}"
            )

            print(
                "Supporting Evidence:",
                result.supporting_evidence_ids
            )

            print(
                "Contradicting Evidence:",
                result.contradicting_evidence_ids
            )

            print(
                f"Explanation: {result.explanation}"
            )

        print("Verdict:", verification_result.verdict)

        print("Confidence:", verification_result.confidence)

        print("Explanation:", verification_result.explanation)

        # ====================================================
        # STEP 5: ORCHESTRATOR DECISION
        # ====================================================

        print("\n========== ORCHESTRATOR DECISION ==========")

        # ----------------------------------------------------
        # SUFFICIENT EVIDENCE
        # ----------------------------------------------------
        if verification_result.verdict in ["SUPPORTED", "REFUTED"]:

            print(
                "Evidence is sufficient. "
                "Verification complete."
            )

            break

        # ----------------------------------------------------
        # INSUFFICIENT EVIDENCE
        # ----------------------------------------------------

        insufficient_subclaim_ids = (get_insufficient_subclaim_ids(verification_result))

        print("\nSubclaims requiring more evidence:",insufficient_subclaim_ids)

        if verification_result.verdict == "INSUFFICIENT":

            # If another attempt is available, retry.
            if attempt < MAX_RETRIES:

                print(
                    "Evidence is insufficient."
                )

                print(
                    "Orchestrator decision: "
                    "retry evidence retrieval."
                )

                # --------------------------------------------
                # PREPARE PREVIOUS QUERIES
                # --------------------------------------------

                # search_queries may contain:
                #
                # - SearchQuery objects
                # - plain strings from an earlier retry
                #
                # Convert both forms into strings before
                # sending them to the retry-query generator.
                previous_query_strings = [
                    search.query
                    if hasattr(search, "query")
                    else search
                    for search in search_queries
                ]

                insufficient_subclaims = [
                    subclaim
                    for subclaim in analysis.subclaims
                    if subclaim.id in insufficient_subclaim_ids
                ]

                current_subclaims = insufficient_subclaims

                # --------------------------------------------
                # GENERATE IMPROVED QUERIES
                # --------------------------------------------

                new_queries = generate_retry_queries(
                    claim=analysis.original_claim,
                    subclaims=insufficient_subclaims,
                    previous_queries=previous_query_strings,
                    verification_explanation=(verification_result.explanation)
                )

                print("\nPrevious Search Queries:")
                for query in previous_query_strings:
                    print("-", query)

                print("\nImproved Search Queries:")
                for search in new_queries:
                    print(
                        f"- {search.subclaim_id}: "
                        f"{search.query}"
                    )

                if new_queries:
                    search_queries = new_queries

            else:

                print(
                    "Evidence is still insufficient."
                )

                print(
                    "Maximum retrieval attempts reached."
                )

    # ========================================================
    # STEP 6: FINAL RESULT
    # ========================================================

    print("\n==========================================")
    print("              FINAL RESULT")
    print("==========================================")

    print("Verdict:", verification_result.verdict)

    print("Confidence:", verification_result.confidence)

    print("Supporting Evidence:",verification_result.supporting_evidence_ids)

    print("Contradicting Evidence:",verification_result.contradicting_evidence_ids)

    print("Explanation:",verification_result.explanation)

    # ========================================================
    # RETURN COMPLETE RESULT
    # ========================================================

    return {
        "status": "completed",
        "analysis": analysis,
        "evidence_result": evidence_result,
        "verification_result": verification_result
    }


# ============================================================
# TERMINAL TEST
# ============================================================

if __name__ == "__main__":

    user_claim = input("Enter a claim: ")

    run_agentic_orchestrator(user_claim)