"""
Agentic Orchestrator
--------------------

Controls the multi-agent fact-verification workflow.

Unlike pipeline.py, which follows a fixed sequence,
this orchestrator can make decisions based on agent outputs.

Current capabilities:
    - Run Claim Agent
    - Run Evidence Agent
    - Run Verification Agent
    - Stop when evidence supports/refutes the claim
    - Retry when evidence is insufficient
    - Generate improved search queries for retry
    - Preserve subclaim/query provenance during
      the initial evidence retrieval
"""

import json

from groq import Groq
from pydantic import BaseModel

from src.agents.claim_agent import analyze_claim
from src.agents.evidence_agent import retrieve_evidence
from src.agents.verification_agent import (prepare_evidence, verify_claim_by_subclaims)

# Maximum number of evidence retrieval attempts.
MAX_RETRIES = 2

class RetrySearchQuery(BaseModel):
    """
    Structured search query generated by the orchestrator
    during an evidence-retrieval retry.

    Keeping subclaim_id allows the Evidence Agent to continue
    performing per-subclaim ranking on later attempts.
    """

    subclaim_id: str
    query: str

# ============================================================
# RETRY QUERY GENERATION
# ============================================================

def generate_retry_queries(claim, subclaims, previous_queries, verification_explanation):
    """
    Generate improved search queries when the previous
    evidence retrieval attempt was insufficient.

    Each generated query must be linked to a valid subclaim.
    """

    client = Groq()

    # --------------------------------------------------------
    # PREPARE SUBCLAIMS FOR THE LLM
    # --------------------------------------------------------

    subclaim_data = [
        {
            "id": subclaim.id,
            "text": subclaim.text
        }
        for subclaim in subclaims
    ]

    prompt = f"""
        You are controlling the evidence retrieval strategy of a
        fact-verification system.

        The previous evidence retrieval attempt was insufficient.

        ORIGINAL CLAIM:
        {claim}

        SUBCLAIMS:
        {json.dumps(subclaim_data, indent=2)}

        PREVIOUS SEARCH QUERIES:
        {json.dumps(previous_queries, indent=2)}

        WHY THE EVIDENCE WAS INSUFFICIENT:
        {verification_explanation}

        Generate improved web search queries that specifically address the missing evidence.

        Every query MUST be linked to one of the provided subclaim IDs.

        Rules:
        - Generate 2 to 4 queries.
        - Use ONLY subclaim IDs listed in SUBCLAIMS.
        - Each query must target the fact expressed by its subclaim.
        - Preserve important entities, dates, locations, events, relationships, negations, and qualifiers.
        - Do not assume the claim is true.
        - Queries must be neutral.
        - Do not simply repeat previous queries.
        - Focus on information missing from the previous evidence.
        - If a particular subclaim lacks sufficient evidence, prioritize queries for that subclaim.
        - Do not invent new subclaims.
        - Return ONLY valid JSON.

        Required format:

        {{
            "queries": [
                {{
                    "subclaim_id": "c1",
                    "query": "improved neutral search query"
                }},
                {{
                    "subclaim_id": "c2",
                    "query": "improved neutral search query"
                }}
            ]
        }}
    """

    response = client.chat.completions.create(
        model="openai/gpt-oss-120b",
        temperature=0,
        max_tokens=500,
        messages=[
            {"role": "user", "content": prompt}
        ]
    )

    # Read the model response.
    text = response.choices[0].message.content.strip()

    # Remove Markdown code fences if the model adds them.
    if text.startswith("```"):
        text = text.strip("`")

        if text.startswith("json"):
            text = text[4:].strip()

    # Convert the JSON response into a Python dictionary.
    data = json.loads(text)

    raw_queries = data.get("queries", [])

    # --------------------------------------------------------
    # VALIDATE SUBCLAIM IDs
    # --------------------------------------------------------

    valid_subclaim_ids = {subclaim.id for subclaim in subclaims}

    retry_queries = []

    for item in raw_queries:

        subclaim_id = item.get("subclaim_id")
        query = item.get("query", "").strip()

        # Ignore malformed queries.
        if not query:
            continue

        # Do not allow the LLM to invent subclaim IDs.
        if subclaim_id not in valid_subclaim_ids:
            continue

        retry_queries.append(
            RetrySearchQuery(
                subclaim_id=subclaim_id,
                query=query
            )
        )

    return retry_queries

# ============================================================
# AGENTIC ORCHESTRATOR
# ============================================================

def run_agentic_orchestrator(user_claim: str):
    """
    Run the agentic fact-verification workflow.
    """

    print("\n==========================================")
    print("       AGENTIC FACT VERIFICATION")
    print("==========================================")

    # ========================================================
    # STEP 1: CLAIM ANALYSIS
    # ========================================================

    print("\n========== CLAIM AGENT ==========")

    analysis = analyze_claim(user_claim)

    print("Status:", analysis.status)

    print("\nSubclaims:")
    for subclaim in analysis.subclaims:
        print(
            f"{subclaim.id}: "
            f"{subclaim.text}"
        )

    print("\nSearch Queries:")
    for search in analysis.search_queries:
        print(
            f"{search.subclaim_id}: "
            f"{search.query}"
        )

    # ========================================================
    # STEP 2: HANDLE AMBIGUOUS CLAIMS
    # ========================================================

    if analysis.status == "needs_clarification":

        print(
            "\n========== ORCHESTRATOR DECISION =========="
        )

        print(
            "Claim requires clarification."
        )

        print("\nAmbiguities:")
        for ambiguity in analysis.ambiguities:
            print("-", ambiguity)

        return {
            "status": "needs_clarification",
            "analysis": analysis,
            "evidence_result": None,
            "verification_result": None
        }

    # ========================================================
    # STEP 3: PREPARE INITIAL SEARCH QUERIES
    # ========================================================

    # IMPORTANT:
    #
    # Previously we converted SearchQuery objects into strings.
    #
    # Now we preserve the complete objects so that the
    # Evidence Agent knows which query belongs to which
    # subclaim.
    search_queries = analysis.search_queries
    evidence_result = None
    verification_result = None

    # ========================================================
    # STEP 4: AGENTIC RETRY LOOP
    # ========================================================

    for attempt in range(1, MAX_RETRIES + 1):

        print(
            f"\n========== EVIDENCE ATTEMPT "
            f"{attempt}/{MAX_RETRIES} =========="
        )

        # ----------------------------------------------------
        # CALL EVIDENCE AGENT
        # ----------------------------------------------------

        evidence_result = retrieve_evidence(
            claim=analysis.original_claim,
            search_queries=search_queries,
            subclaims=analysis.subclaims
        )

        evidence_count = len(evidence_result["evidence"])

        print(
            f"\nRetrieved {evidence_count} "
            "evidence item(s)."
        )

        # ====================================================
        # DISPLAY EVIDENCE PROVENANCE
        # ====================================================

        # This allows us to verify that each evidence item
        # remembers which subclaim/query retrieved it.
        print("\nEvidence Provenance:")

        for index, item in enumerate(evidence_result["evidence"], start=1):
            print(
                f"[{index}] "
                f"Subclaim: {item.get('subclaim_id')} | "
                f"Query: {item.get('query')} | "
                f"URL: {item.get('url')}"
            )

        # ====================================================
        # PREPARE EVIDENCE FOR VERIFICATION AGENT
        # ====================================================

        verification_evidence = prepare_evidence(evidence_result["evidence"])

        print("\nEvidence received by Verification Agent:")

        for item in verification_evidence:
            print(
                f"Evidence {item.id} | "
                f"Subclaim: {item.subclaim_id} | "
                f"Query: {item.query}"
            )

        # ----------------------------------------------------
        # CALL VERIFICATION AGENT
        # ----------------------------------------------------

        print("\n========== VERIFICATION AGENT ==========")

        verification_result = verify_claim_by_subclaims(
            subclaims=analysis.subclaims,
            evidence=verification_evidence
        )

        print("\nSubclaim Verification Results:")

        for result in verification_result.subclaim_results:

            print(
                f"\n{result.subclaim_id}: "
                f"{result.subclaim_text}"
            )

            print(
                f"Verdict: {result.verdict}"
            )

            print(
                f"Confidence: {result.confidence}"
            )

            print(
                "Supporting Evidence:",
                result.supporting_evidence_ids
            )

            print(
                "Contradicting Evidence:",
                result.contradicting_evidence_ids
            )

            print(
                f"Explanation: {result.explanation}"
            )

        print("Verdict:", verification_result.verdict)

        print("Confidence:", verification_result.confidence)

        print("Explanation:", verification_result.explanation)

        # ====================================================
        # STEP 5: ORCHESTRATOR DECISION
        # ====================================================

        print("\n========== ORCHESTRATOR DECISION ==========")

        # ----------------------------------------------------
        # SUFFICIENT EVIDENCE
        # ----------------------------------------------------
        if verification_result.verdict in ["SUPPORTED", "REFUTED"]:

            print(
                "Evidence is sufficient. "
                "Verification complete."
            )

            break

        # ----------------------------------------------------
        # INSUFFICIENT EVIDENCE
        # ----------------------------------------------------

        if verification_result.verdict == "INSUFFICIENT":

            # If another attempt is available, retry.
            if attempt < MAX_RETRIES:

                print(
                    "Evidence is insufficient."
                )

                print(
                    "Orchestrator decision: "
                    "retry evidence retrieval."
                )

                # --------------------------------------------
                # PREPARE PREVIOUS QUERIES
                # --------------------------------------------

                # search_queries may contain:
                #
                # - SearchQuery objects
                # - plain strings from an earlier retry
                #
                # Convert both forms into strings before
                # sending them to the retry-query generator.
                previous_query_strings = [
                    search.query
                    if hasattr(search, "query")
                    else search
                    for search in search_queries
                ]

                # --------------------------------------------
                # GENERATE IMPROVED QUERIES
                # --------------------------------------------

                new_queries = generate_retry_queries(
                    claim=analysis.original_claim,
                    subclaims=analysis.subclaims,
                    previous_queries=previous_query_strings,
                    verification_explanation=(verification_result.explanation)
                )

                print("\nPrevious Search Queries:")
                for query in previous_query_strings:
                    print("-", query)

                print("\nImproved Search Queries:")
                for search in new_queries:
                    print(
                        f"- {search.subclaim_id}: "
                        f"{search.query}"
                    )

                if new_queries:
                    search_queries = new_queries

            else:

                print(
                    "Evidence is still insufficient."
                )

                print(
                    "Maximum retrieval attempts reached."
                )

    # ========================================================
    # STEP 6: FINAL RESULT
    # ========================================================

    print("\n==========================================")
    print("              FINAL RESULT")
    print("==========================================")

    print("Verdict:", verification_result.verdict)

    print("Confidence:", verification_result.confidence)

    print("Supporting Evidence:",verification_result.supporting_evidence_ids)

    print("Contradicting Evidence:",verification_result.contradicting_evidence_ids)

    print("Explanation:",verification_result.explanation)

    # ========================================================
    # RETURN COMPLETE RESULT
    # ========================================================

    return {
        "status": "completed",
        "analysis": analysis,
        "evidence_result": evidence_result,
        "verification_result": verification_result
    }


# ============================================================
# TERMINAL TEST
# ============================================================

if __name__ == "__main__":

    user_claim = input("Enter a claim: ")

    run_agentic_orchestrator(user_claim)