# searching internet

import os

from dotenv import load_dotenv
from tavily import TavilyClient


# Load variables stored inside the .env file.
# This allows us to access TAVILY_API_KEY without
# writing the secret key directly in our Python code.
load_dotenv()

def search_web(query, max_results=5):
    """
    Search the web for evidence related to a query.

    Parameters:
        query (str): Search query generated by the Claim Agent.
        max_results (int): Maximum number of search results to retrieve.

    Returns: list: A list containing structured search results.
    """
    
    # Read our Tavily API key from the environment.
    api_key = os.getenv("TAVILY_API_KEY")

    # Stop early if the API key has not been configured.
    if not api_key:
        raise ValueError("TAVILY_API_KEY was not found.""Please add it to your .env file.")

    # Create the Tavily search client.
    client = TavilyClient(api_key=api_key)

    # Send the query to Tavily.
    response = client.search(query=query, max_results=max_results)

    # We don't want the rest of our project to depend directly on Tavily's response structure.
    # Therefore, convert the results into our own common format.
    results = []

    for result in response.get("results", []):
        results.append({
            "title": result.get("title", ""),
            "url": result.get("url", ""),
            "snippet": result.get("content", "")
        })
    return results


# This block runs only when this file is executed directly.
# It is useful while testing this module independently.
if __name__ == "__main__":

    test_query = "Chandrayaan-3 launch date ISRO"

    search_results = search_web(test_query)

    for index, result in enumerate(search_results, start=1):
        print(f"\n--- Result {index} ---")
        print("Title:", result["title"])
        print("URL:", result["url"])
        print("Snippet:", result["snippet"])