# connecting all four retrieval components together

from src.retrieval.web_search import search_web
from src.retrieval.content_extractor import extract_content
from src.retrieval.text_chunker import chunk_text
from src.retrieval.evidence_ranker import rank_evidence


def retrieve_evidence(claim, search_queries, max_results_per_query=3, top_k=5):
    """
    Complete Evidence Retrieval Agent.

    The agent:
        1. Searches the web
        2. Downloads relevant webpages
        3. Extracts webpage content
        4. Splits content into passages
        5. Ranks passages against the claim
        6. Returns the strongest evidence

    Parameters:
        claim (str): Original claim entered by the user.

        search_queries (list[str]): Queries produced by the Claim Agent.

    Returns:
        list[dict]: Top evidence passages with source information.
    """

    all_passages = []

    # Search each query generated by the Claim Agent.
    for query in search_queries:

        print(f"\nSearching: {query}")

        search_results = search_web(query, max_results=max_results_per_query)

        # Process every webpage returned by the search.
        for result in search_results:

            url = result["url"]

            print(f"Reading: {url}")

            # Extract readable content from the webpage.
            content = extract_content(url)

            # Skip webpages that couldn't be extracted.
            if not content:
                continue

            # Break the webpage into smaller passages.
            chunks = chunk_text(content)

            # Preserve the source information for EVERY
            # chunk so we always know where evidence came from.
            for chunk in chunks:
                all_passages.append({"text": chunk, "title": result["title"], "url": url})

    # Rank all collected passages against the original claim.
    top_evidence = rank_evidence(claim, all_passages, top_k=top_k)

    return {
        "claim": claim,
        "evidence": top_evidence
    }


if __name__ == "__main__":

    # For now we manually provide what the Claim Agent will eventually send us.
    test_claim = (
        "ChatGPT is in loss."
    )

    test_queries = [
        "OpenAI ChatGPT profit or loss financial performance",
        "OpenAI ChatGPT revenue losses profitability"
    ]

    evidence = retrieve_evidence(test_claim, test_queries)

    print("\n\n========== TOP EVIDENCE ==========")

    print("\nClaim:", evidence["claim"])

    for index, item in enumerate(evidence["evidence"], start=1):
        print(f"\nEvidence {index}")
        print("Relevance:", round(item["relevance_score"], 3))
        print("Title:", item["title"])
        print("URL:", item["url"])
        print("Text:", item["text"])