# connecting all four retrieval components together

from src.retrieval.web_search import search_web
from src.retrieval.content_extractor import extract_content
from src.retrieval.text_chunker import chunk_text
from src.retrieval.evidence_ranker import rank_evidence


def retrieve_evidence(claim, search_queries, max_results_per_query=3, top_k=5):
    """
    Complete Evidence Retrieval Agent.

    The agent:
        1. Searches the web
        2. Downloads relevant webpages
        3. Extracts webpage content
        4. Splits content into passages
        5. Ranks passages against the claim
        6. Returns the strongest evidence

    Parameters:
        claim (str): Original claim entered by the user.

        search_queries (list[str]): Queries produced by the Claim Agent.

    Returns:
        list[dict]: Top evidence passages with source information.
    
    Retrieve and rank web evidence for a claim.

    search_queries can contain:

    1. SearchQuery objects from the Claim Agent:
       - subclaim_id
       - query

    2. Plain string queries:
       - Used by orchestrator-generated retry queries.

    Each retrieved evidence passage keeps track of:
       - which subclaim it belongs to
       - which search query retrieved it
       - source title
       - source URL
       - evidence text
       - relevance score
    """

    all_passages = []

    # ========================================================
    # PROCESS EACH SEARCH QUERY
    # ========================================================

    for search_item in search_queries:

        # ----------------------------------------------------
        # CASE 1:
        # SearchQuery object produced by Claim Agent
        # ----------------------------------------------------

        if hasattr(search_item, "query"):
            query = search_item.query
            subclaim_id = search_item.subclaim_id

        # ----------------------------------------------------
        # CASE 2:
        # Plain string query produced by orchestrator retry
        # ----------------------------------------------------

        else:
            query = search_item
            subclaim_id = None

        print(f"\nSearching: {query}")

        # ====================================================
        # WEB SEARCH
        # ====================================================

        search_results = search_web(query, max_results=max_results_per_query)

        # ====================================================
        # PROCESS SEARCH RESULTS
        # ====================================================

        for result in search_results:

            url = result["url"]

            print(f"Reading: {url}")

            # Extract useful text from the webpage.
            content = extract_content(url)

            # Skip pages where extraction failed.
            if not content:
                continue

            # Split large webpage text into smaller passages.
            chunks = chunk_text(content)

            # =================================================
            # STORE PASSAGES WITH PROVENANCE
            # =================================================

            for chunk in chunks:

                all_passages.append({
                    # Which Claim Agent subclaim caused
                    # this evidence to be retrieved.
                    "subclaim_id": subclaim_id,

                    # Exact search query that retrieved it.
                    "query": query,

                    # Evidence content.
                    "text": chunk,

                    # Source information.
                    "title": result["title"],
                    "url": url
                })

        # ========================================================
        # RANK EVIDENCE
        # ========================================================

        # The existing Evidence Ranker calculates semantic
        # similarity between the original claim and every
        # retrieved passage.
        #
        # It also adds:
        #
        #     relevance_score
        #
        # to each evidence dictionary.
        top_evidence = rank_evidence(claim, all_passages, top_k=top_k)

    # ========================================================
    # RETURN RESULT
    # ========================================================

    return {
        "claim": claim,
        "evidence": top_evidence
    }

    # Search each query generated by the Claim Agent.
    # for query in search_queries:

    #     print(f"\nSearching: {query}")

    #     search_results = search_web(query, max_results=max_results_per_query)

    #     # Process every webpage returned by the search.
    #     for result in search_results:

    #         url = result["url"]

    #         print(f"Reading: {url}")

    #         # Extract readable content from the webpage.
    #         content = extract_content(url)

    #         # Skip webpages that couldn't be extracted.
    #         if not content:
    #             continue

    #         # Break the webpage into smaller passages.
    #         chunks = chunk_text(content)

    #         # Preserve the source information for EVERY
    #         # chunk so we always know where evidence came from.
    #         for chunk in chunks:
    #             all_passages.append({"text": chunk, "title": result["title"], "url": url})

    # # Rank all collected passages against the original claim.
    # top_evidence = rank_evidence(claim, all_passages, top_k=top_k)

    # return {
    #     "claim": claim,
    #     "evidence": top_evidence
    # }